import Head from "next/head";
import Image from "next/image";

import Header from "./components/header";
import Main_bg from "./main_bg";

export default function Home() {
  return (
    <>
      <Head>
        <title>second thoughts are best</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/second-thoghts-are-best_favicon.svg" />
      </Head>

      <Main_bg></Main_bg>
    </>
  );
}
