import Head from 'next/head'
import Image from 'next/image'

import Header from "./components/header"
import Main_bg from "./components/main_bg"

export default function Home() {
  
  return (
    <div>
      {/* <Main_Bg> */}
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <Header></Header>
  
        <Main_bg></Main_bg>
        <footer>footer</footer>
      {/* </Main_Bg> */}
    </div>
  )
}
