
import Head from 'next/head'
import Image from 'next/image'

import Header from "./components/header"
// import Footer from "./components/footer"
// import Banner from "./components/banner"
import Main_bg from "./components/main_bg"

export default function Home() {
  
  return (
    <div>
        {/* <Banner></Banner> */}
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <Header></Header>
  
        <div><Main_bg></Main_bg></div>

        {/* <Footer></Footer> */}


    </div>
  )
}
